server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: edu-oauth
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.214.213:8848
      config:
        server-addr: 47.115.214.213:8848
        file-extension: yaml
        refresh-enabled: true # ??????,???false
        import-check:
          enabled: false # ????????????,???true
  config:
    import: nacos:edu-oauth-dev.yaml
dubbo:
  application:
    name: edu-oauth
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.hatcher.oauth.remote
  registry:
    address: nacos://47.115.214.213:8848
#  config-center:
#    address: nacos://47.115.214.213:8848
#    config-file: edu-ad-dev.yaml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # ????????????