server:
  port: 9001

spring:
  application:
    name: edu-gateway-boot
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.214.213:8848
    gateway:
      routes:
        - id: edu-front
          uri: lb://edu-front-boot
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
        - id: edu-admin
          uri: lb://edu-admin-boot
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1